apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - image: ikramer/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
          ports:
          - containerPort: 3111
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4111
              initialDelaySeconds: 15
              periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4111
              initialDelaySeconds: 5
              periodSeconds: 5
