apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: exercises/argocd/exercise_3/helm/python-helloworld
    repoURL: https://github.com/anajoy/nd064_course_1
    targetRevision: HEAD
